version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diocesis
    volumes:
      - $HOME/docker_volumes/pg_data_diocesis:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  serve:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=diocesis
    links:
      - postgres

volumes:
  postgres_data:
